spring:
  cloud:
    gateway:
      routes:
        - id: payment_routh #payment_route    #???ID????????????????????
          uri: http://localhost:8081          #????????????
          predicates:
            - Path=/api/**
        - id: vue
          uri: http://localhost:3000
          predicates:
            - Path=/vue/**