
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/books
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: cloud-gateway
server:
  port: 8081